import tkinter as tk
top = tk.Tk()
top.config(cursor="circle")
frame = tk.Frame(top)
frame.pack()
leftframe = tk.Frame(top)
leftframe.pack(side=tk.LEFT)
rightframe = tk.Frame(top)
rightframe.pack(side=tk.RIGHT)
btn1 = tk.Button(frame,text="Submit",foreground="red",activebackground="yellow")
btn1.pack(side=tk.LEFT)
btn2 = tk.Button(frame,text="Remove",foreground="brown",activebackground="blue")
btn2.pack(side=tk.RIGHT)
btn3 = tk.Button(rightframe,text="Add",foreground="blue",activebackground="yellow")
btn3.pack(side=tk.LEFT)

btn4 = tk.Button(leftframe,text="Modify",foreground="black",activebackground="yellow")
btn4.pack(side=tk.RIGHT)
top.mainloop()
