from tkinter import *
top = Tk()
Lb = Listbox(top)
Lb.insert(1,"Python")
Lb.insert(2,"Java")
Lb.insert(3,"C++")
Lb.insert(4,"C#")
Lb.insert(5,".NET")
Lb.insert(6,"Any other")
Lb.pack()
top.mainloop()
