import tkinter
top = tkinter.Tk()
top.title("hello...")
name=tkinter.Label(top,text="Name : ")
name.place(x=10,y=50)
e1 = tkinter.Entry(top)
pwd = tkinter.Label(top,text="Password : ")
pwd.place(x=10,y=80)
e2 = tkinter.Entry(top)
e1.place(x=80,y=50)
e2.place(x=80,y=80)
b1 = tkinter.Button(top,text="Submit",foreground="blue",background="yellow",activebackground="magenta",bd=5)
b1.place(x=40,y=120)
top.mainloop()
